### ISSUE TITLE
Add more function

### ISSUE THREAD

**Issue by nguyencongminh090** [wuwbobo2021/figrid-board#2]
- Export : It is a little same as Export Library -> Text 
- Convert from text to Lib: 
+ I have a text file contain a lot of game and I want to convert it to Renlib file, each line in text file 1 game and now you just only add that game to Tree then save it.

**Comment by wuwbobo2021** [comment]
I think it might be a special function... You can try to do this at first: `figrid -p <libraryfile> 0<input.txt 1>output.txt`, then write "search\n" into `input.txt`, then wait for a while, open `output.txt`, delete 1 line at the beginning and 2 lines at the end, then the remaining will be what you want. Then you can do it in an advanced way with Python, I used to think it's easy for you.

**Comment by wuwbobo2021** [comment]
For the second request you've just added, that's what I want to know: if I were to add all the functions you need into my program, then where would be the functionality of your project? Just input the lines into my program, input `root\n` after each line.

**Comment by nguyencongminh090** [comment]
All right, I need some function same as in Renlib program because I can't communicate with Renlib program.

**Comment by nguyencongminh090** [comment]
`figrid -p <libraryfile> 0<input.txt> 1<output.txt>`
 - Library is my .lib file and <input.txt> is ?, I still not understand this why not
`figrid -p <libraryfile> <output.txt>`

**Comment by nguyencongminh090** [comment]
`search` is good but it return lots of line for a game in lib, I think it is better if you can return a completely game.
Example: 
```
a1
a1 a2 
a1 a2 a3
```
to
```
a1 a2 a3
```
About convert from text to Lib, I know how to deal with it now. Thanks.

**Comment by wuwbobo2021** [comment]
I've just modified my program to skip output of nodes that have exactly one descendent, you can test it again.

**Comment by nguyencongminh090** [comment]
Thanks for you try but it still not same as I hope. This is my lib: [Test.txt](https://github.com/wuwbobo2021/figrid-board/files/7968664/Test.txt). You can test it, if I input search (without any parameter) it should give me:
```
h3 e8 m5 f8 k3 g8
h3 e8 m5 g8 k3 f8
```
NOTE: I can't upload .lib file so I rename it to .txt

**Comment by wuwbobo2021** [comment]
Did you mean you only want output of leaves? I changed my program again.

**Comment by nguyencongminh090** [comment]
`figrid -p <libraryfile> 0<input.txt 1>output.txt`
Is there some problem with this comment? It doesn't excute the command inside input.txt

> Did you mean you only want output of leaves? I changed my program again.

Yes, it is.

**Comment by wuwbobo2021** [comment]
I'm sorry, it's a simple problem: an enumeration variable in the new struct variable won't be initialized implicitly. That had caused the problem: the search mode became `Node_Search_Mark`, but I had expected it to be `Node_Search_None = 0`. I've fixed the prpblem.

**Comment by nguyencongminh090** [comment]
Thanks!
